import { chromium } from '@playwright/test'
const browser = await chromium.launch()
for (const [name, vp, mobile] of [['m', { width: 390, height: 844 }, true], ['d', { width: 1440, height: 900 }, false]]) {
  const ctx = await browser.newContext({ viewport: vp, isMobile: mobile, hasTouch: mobile, deviceScaleFactor: 2 })
  const page = await ctx.newPage()
  page.on('console', (m) => { if (m.type() === 'error') console.log(name, 'console error', m.text()) })
  await page.goto('http://127.0.0.1:5180/')
  await page.screenshot({ path: `/tmp/shots/${name}-login.png` })
  await page.getByLabel('Correo').fill('ana@ungim.test')
  await page.getByLabel('Contraseña').fill('donuts')
  await page.getByRole('button', { name: 'Entrar' }).click()
  await page.getByRole('heading', { name: /Hola, Ana/ }).waitFor()
  await page.waitForTimeout(1200)
  await page.screenshot({ path: `/tmp/shots/${name}-today.png`, fullPage: true })
  await page.getByRole('button', { name: 'Sí' }).first().click()
  await page.getByRole('button', { name: 'Entrené' }).click()
  await page.waitForTimeout(900)
  await page.screenshot({ path: `/tmp/shots/${name}-today-done.png` })
  await page.getByRole('button', { name: 'Marcador' }).click()
  await page.waitForTimeout(1400)
  await page.screenshot({ path: `/tmp/shots/${name}-score.png`, fullPage: true })
  await page.getByRole('button', { name: 'Historial' }).click()
  await page.waitForTimeout(1000)
  await page.screenshot({ path: `/tmp/shots/${name}-history.png`, fullPage: true })
  await page.getByRole('button', { name: /vie, 2 oct/ }).first().click()
  await page.waitForTimeout(700)
  await page.screenshot({ path: `/tmp/shots/${name}-daysheet.png` })
  await page.keyboard.press('Escape')
  await page.waitForTimeout(500)
  await page.getByRole('button', { name: /Cuenta de/ }).click()
  await page.waitForTimeout(600)
  await page.getByRole('button', { name: 'Ajustar mi plan' }).click()
  await page.waitForTimeout(800)
  await page.screenshot({ path: `/tmp/shots/${name}-plan.png` })
  await ctx.close()
}
await browser.close()
